### ISSUE TITLE
Unable to run create_obsmodel 

### ISSUE THREAD

**Issue by christinawlindberg** [BEAST-Fitting/beast#568] opened 2020-05-22 06:40 UTC
So sorry to bother again. I've run into an issue creating the noise models. When I run the function
`create_obsmodel.create_obsmodel(
        use_sd=True, nsubs=datamodel.n_subgrid, nprocs=1
    )`

it comes back with the error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-39-65a4ae277439> in <module>
      1 # create the noise model with our ASTs
      2 create_obsmodel.create_obsmodel(
----> 3         use_sd=True, nsubs=datamodel.n_subgrid, nprocs=1
      4     )

~/anaconda3/envs/astroconda/lib/python3.6/site-packages/beast/tools/run/create_obsmodel.py in create_obsmodel(use_sd, nsubs, nprocs, subset, use_rate)
     86             input_list = [(modelsedgridfile, curr_sd) for curr_sd in sd_list]
     87 
---> 88             parallel_wrapper(gen_obsmodel, input_list, nprocs=nprocs)
     89 
     90         # if we're not splitting by source density

~/anaconda3/envs/astroconda/lib/python3.6/site-packages/beast/tools/run/helper_functions.py in parallel_wrapper(function, arg_tuples, nprocs)
     59     else:
     60         for a in arg_tuples:
---> 61             r = function(*a)
     62             print(r)
     63 

~/anaconda3/envs/astroconda/lib/python3.6/site-packages/beast/tools/run/create_obsmodel.py in gen_obsmodel(modelsedgridfile, source_density, use_rate)
    179             modelsedgrid,
    180             absflux_a_matrix=datamodel.absflux_a_matrix,
--> 181             use_rate=use_rate,
    182         )
    183 

~/anaconda3/envs/astroconda/lib/python3.6/site-packages/beast/observationmodel/noisemodel/generic_noisemodel.py in make_toothpick_noise_model(outname, astfile, sedgrid, use_rate, vega_fname, absflux_a_matrix, **kwargs)
     92 
     93     # evaluate the noise model for all the models in sedgrid
---> 94     bias, sigma, compl = model(sedgrid)
     95 
     96     # absolute flux calibration uncertainties

~/anaconda3/envs/astroconda/lib/python3.6/site-packages/beast/observationmodel/noisemodel/toothpick.py in __call__(self, sedgrid, **kwargs)
    362 
    363     def __call__(self, sedgrid, **kwargs):
--> 364         return self.interpolate(sedgrid, **kwargs)

~/anaconda3/envs/astroconda/lib/python3.6/site-packages/beast/observationmodel/noisemodel/toothpick.py in interpolate(self, sedgrid, progress)
    355             _fluxes = _fluxes[arg_sort]
    356 
--> 357             bias[:, i] = np.interp(flux[:, i], _fluxes, _biases[arg_sort])
    358             sigma[:, i] = np.interp(flux[:, i], _fluxes, _sigmas[arg_sort])
    359             compl[:, i] = np.interp(flux[:, i], _fluxes, _compls[arg_sort])

<__array_function__ internals> in interp(*args, **kwargs)

~/anaconda3/envs/astroconda/lib/python3.6/site-packages/numpy/lib/function_base.py in interp(x, xp, fp, left, right, period)
   1410         fp = np.concatenate((fp[-1:], fp, fp[0:1]))
   1411 
-> 1412     return interp_func(x, xp, fp, left, right)
   1413 
   1414 

ValueError: array of sample points is empty
```

I've tried to go in and see if there's potentially anything wrong with the data files I'm using but I didn't see any obvious issue. I was using this function on an earlier development version without any problems, and the data files have remained relatively the same. I'm hoping someone might have an idea of what could be going on...

**Comment by karllark** [comment] 2020-05-22 17:34
This sounds like there is a problem with the AST outputs.  The error looks like the binned models for that band did not have entries.  This seems to imply that there are no AST models somehow.  Can you  provide a bit more info?  Maybe a link to the AST outputs?  A bit more info needed to help debug this. 

Once we have figured out what the issue is, I'd advocate adding a test for what caused this error.  I do feel it is something about the AST output file.

**Comment by karllark** [comment] 2020-05-22 17:35
BTW, no apology needed.  You are doing *exactly* the right thing by raising an issue.  I really appreciate you raising issues like this.

**Comment by christinawlindberg** [comment] 2020-05-22 18:19
Are you saying that there might be an issue with the ASTs once they've been sorted by source density? Sorry, I don't completely understand what you're referring to with AST outputs.

**Comment by karllark** [comment] 2020-05-22 18:42
I think there is some issue with the the ASTs used in creating the observation model.  I refer to these are the AST outputs as they are the result of taking the AST inputs, sending them to Ben, and then getting the results (AST outputs).  These AST outputs are then input into the observation model code to make the observation model.  The traceback you posted seems to indicate that the observation model is empty, hence I am concerned that there is some issue with the AST outputs input into this step.  The automated tests are working, hence the code is still producing an observation model given the cached AST outputs for phat_small.  But not for you with these AST outputs.  There have been changes in this code for v1.4 and so I wonder if something changed that was not caught by the automated tests - or the tests that @lea-hagen has been running offline.

**Comment by christinawlindberg** [comment] 2020-05-22 19:11
I took a look at the AST output file it failed on ("M31-B09-EAST_chunk.gst.fake_cut_bin2.fits") and it seems to be reasonably populated. 

I think the current M31 example notebook also failed at this step (Step 7) for Claire (and now me after I upgraded my BEAST version). Is there any more info I could provide to help? Please let me know.

**Comment by karllark** [comment] 2020-05-22 19:16
At this point, debugging requires actually seeing the file and the code you are using.

**Comment by christinawlindberg** [comment] 2020-05-22 19:55
Is there a good place for me to share the notebook I'm using? It automatically fetches all the data needed to run. After that, someone would just need to run steps 1, 2, (3 can be skipped), 4, 5, 6, and then 7 where it breaks. Only step 2 should really take any time to run (~2 minutes).

**Comment by karllark** [comment] 2020-05-22 20:04
Are you saving this notebook to some github repository?  That would be ideal as it would easy to get it.  If not, then I guess email?  If you clear all the outputs before saving it, it shouldn't be too large.

**Comment by lea-hagen** [comment] 2020-05-27 17:12
Another option would be to have a meeting sometime and share your screen.  Not sure if that would be more efficient or not.

**Comment by christinawlindberg** [comment] 2020-06-29 20:41
This issue should hopefully be fixed now. Claire discovered that one of our source density bins for our original small dataset had too few stars to fill each flux bin when making the noise models (I believe she said we needed at least 5 sources per flux bin per source density bin). We fixed this by making our source density areas larger so we'd have fewer pixels.

**Comment by karllark** [comment] 2020-06-29 20:57
Great.  I'll close the issue then.

**Closed by karllark** 2020-06-29 20:57 UTC
Labels: bug, effort-medium
