### ISSUE TITLE
Choose which BEAST files to save forever

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#569] opened 2020-05-27 17:22 UTC
This isn't urgent yet, but we should decide which BEAST output files to save.  Keeping all of them in perpetuity might be too much file space.  Obviously the merged stats/PDFs/lnP files are necessary, and presumably the grids and noisemodels.  I don't know if we need the trimmed grids/noisemodels... I'm pretty sure the grid reference indices (such as in the lnP file) are for the full (rather than trimmed) grid, but we should confirm.

**Comment by karllark** [comment] 2020-05-27 18:09
Is space a real issue?  Getting more disk space is an easy solution to this problem. 

At some level, the trimmed grids/noisemodels can be recreated as long as the full grid/noisemodel is present.

**Comment by galaxyumi** [comment] 2020-05-27 19:03
Aren't the trimmed cats also needed for running tests for some cases? 

I can confirm that the saved indices are for the full grid.

**Comment by lea-hagen** [comment] 2020-05-28 16:46
> Aren't the trimmed cats also needed for running tests for some cases?

I should have clarified, this is for production runs.

> I can confirm that the saved indices are for the full grid.

Awesome!

**Comment by lea-hagen** [comment] 2020-05-28 16:49
> Is space a real issue? Getting more disk space is an easy solution to this problem.

What amount of disk space would you consider to be reasonable?  In my XSEDE proposal, I estimated that I'd need 132 TB.

> At some level, the trimmed grids/noisemodels can be recreated as long as the full grid/noisemodel is present.

True.  And since Yumi pointed out that the indices are indeed for the full grid, I can't immediately think of a use case for the trimmed ones anyway.

**Comment by galaxyumi** [comment] 2020-05-29 03:08
> > Aren't the trimmed cats also needed for running tests for some cases?
> 
> I should have clarified, this is for production runs. What tests are you referring to?
> Ah, I was talking about example files for the reproducibility tests. For production runs, I agree that we don't have to keep trimmed catalogs. One might/can delete these catalogs depending upon their own disk space, and recreate when needed.

**Comment by karllark** [comment] 2020-06-18 17:13
Closing this issue as it looks like the question has been answered.  Reopen if this is incorrect.

**Closed by karllark** 2020-06-18 17:13 UTC
Labels: question
