### ISSUE TITLE
Add functionality for distance fitting.

### ISSUE THREAD

**Issue by drvdputt** [BEAST-Fitting/beast#146] opened 2017-11-27 19:56 UTC
I need this for my work on IC63. Our first thought is that there would just be a grid of distances, for which different models are run in parallel.

**Comment by karllark** [comment] 2017-11-27 21:28
May be duplicate of #38.

**Comment by galaxyumi** [comment] 2017-11-27 21:48
It seems like duplicate. We can work together on this. 
(Still waiting for ASTs for the SMASH data.)

**Comment by karllark** [comment] 2017-11-30 13:19
Closing this issue.  Please use issue #38 to track this work.

**Closed by karllark** 2017-11-30 13:19 UTC
Labels: enhancement
