### ISSUE TITLE
make_extinguished_sed_grid functioning strangely

### ISSUE THREAD

**Issue by christinawlindberg** [BEAST-Fitting/beast#770] opened 2022-04-05 13:07 UTC
I wanted to report this issue in case anyone else has experienced this or in case I find a solution.

When using `make_extinguished_sed_grid`, the function behaves unexpectedly. For example, when I define `rv=[2.0, 6.0, 1.0]`, but don't define fA, it claims there is an Rv input parameter error.

```
extLaw = extinction.Generalized_RvFALaw(ALaw=extinction.Generalized_DustExt(curve='F19'), BLaw=extinction.Generalized_DustExt(curve='G03_SMCBar'))

make_extinguished_sed_grid(project,
                           g_pspec,
                           filters,
                           extLaw=extLaw,
                           av=[0.01, 10.0, 0.5],
                           rv=[2.0, 6.0, 1.0],
                          )
```
```
~/anaconda3/lib/python3.8/site-packages/dust_extinction/baseclasses.py in Rv(self, value)
     82         """
     83         if not (self.Rv_range[0] <= value <= self.Rv_range[1]):
---> 84             raise InputParameterError(
     85                 "parameter Rv must be between "
     86                 + str(self.Rv_range[0])

InputParameterError: parameter Rv must be between 2.0 and 6.0
```

If I define fA `fA=[0.0, 1.0, 0.2]`, the Rv input parameter error is never reached, and the code fails even earlier on with a value error.
```
ValueError: Input x outside of range defined for F19 [0.3 <= x <= 8.7, x has units 1/micron]
```

I couldn't find any recent changes to the function, and I was wondering if anyone else had any idea what could be going wrong.

**Comment by christinawlindberg** [comment] 2022-04-05 13:08
Here is the full error log for the second issue.
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-ddd63af43098> in <module>
      1 extLaw = extinction.Generalized_RvFALaw(ALaw=extinction.Generalized_DustExt(curve='F19'), 
      2                                         BLaw=extinction.Generalized_DustExt(curve='G03_SMCBar'))
----> 3 make_extinguished_sed_grid(project,
      4                            g_pspec,
      5                            filters,

~/anaconda3/lib/python3.8/site-packages/beast/physicsmodel/model_grid.py in make_extinguished_sed_grid(project, specgrid, filters, av, rv, fA, av_prior_model, rv_prior_model, fA_prior_model, extLaw, add_spectral_properties_kwargs, absflux_cov, verbose, seds_fname, filterLib, info_fname, **kwargs)
    487             g.write(seds_fname)
    488         else:
--> 489             for gk in g:
    490                 gk.write(seds_fname, append=True)
    491 

~/anaconda3/lib/python3.8/site-packages/beast/physicsmodel/creategrid.py in make_extinguished_grid(spec_grid, filter_names, extLaw, avs, rvs, fAs, av_prior_model, rv_prior_model, fA_prior_model, chunksize, add_spectral_properties_kwargs, absflux_cov, filterLib)
    398                 dust_prior_weight = av_prior(Av) * rv_prior(Rv) * fA_prior(f_A)
    399                 Rv_MW = extLaw.get_Rv_A(Rv, f_A)
--> 400                 r = g0.applyExtinctionLaw(extLaw, Av=Av, Rv=Rv, f_A=f_A, inplace=False)
    401                 # add extra "spectral bands" if requested
    402                 if add_spectral_properties_kwargs is not None:

~/anaconda3/lib/python3.8/site-packages/beast/physicsmodel/grid.py in applyExtinctionLaw(self, extLaw, inplace, **kwargs)
    296         if not isinstance(extLaw, extinction.ExtinctionLaw):
    297             raise TypeError("Expecting ExtinctionLaw object got %s" % type(extLaw))
--> 298         extCurve = np.exp(-1.0 * extLaw.function(self.lamb[:], **kwargs))
    299         if not inplace:
    300             g = self.copy()

~/anaconda3/lib/python3.8/site-packages/beast/physicsmodel/dust/extinction.py in function(self, lamb, Av, Rv, Alambda, f_A, **kwargs)
    500 
    501         # compute the two components
--> 502         k_A = self.ALaw.function(_lamb, Av=Av, Rv=Rv_A, Alambda=Alambda)
    503         k_B = self.BLaw.function(_lamb, Av=Av, Alambda=Alambda)
    504 

~/anaconda3/lib/python3.8/site-packages/beast/physicsmodel/dust/extinction.py in function(self, lamb, Av, Rv, Alambda, **kwargs)
    667 
    668         if Alambda:
--> 669             return extcurve_obj(_lamb * units.angstrom) * Av
    670         else:
    671             return extcurve_obj(_lamb * units.angstrom) * Av * (np.log(10.0) * 0.4)

~/anaconda3/lib/python3.8/site-packages/astropy/modeling/core.py in __call__(self, model_set_axis, with_bounding_box, fill_value, equivalencies, inputs_map, *inputs, **new_inputs)
    399                            ('inputs_map', None)])
    400 
--> 401             new_call = make_function_with_signature(
    402                 __call__, args, kwargs, varargs='inputs', varkwargs='new_inputs')
    403 

~/anaconda3/lib/python3.8/site-packages/astropy/modeling/core.py in __call__(self, *inputs, **kwargs)
    378             def __call__(self, *inputs, **kwargs):
    379                 """Evaluate this model on the supplied inputs."""
--> 380                 return super(cls, self).__call__(*inputs, **kwargs)
    381 
    382             # When called, models can take two optional keyword arguments:

~/anaconda3/lib/python3.8/site-packages/astropy/modeling/core.py in __call__(self, *args, **kwargs)
    912         new_args, kwargs = self._get_renamed_inputs_as_positional(*args, **kwargs)
    913 
--> 914         return generic_call(self, *new_args, **kwargs)
    915 
    916     def _get_renamed_inputs_as_positional(self, *args, **kwargs):

~/anaconda3/lib/python3.8/site-packages/astropy/modeling/core.py in generic_call(self, *inputs, **kwargs)
   3786             outputs = Quantity(outputs, valid_result_unit, copy=False)
   3787     else:
-> 3788         outputs = self.evaluate(*chain(inputs, parameters))
   3789         if self.n_outputs == 1:
   3790             outputs = (outputs,)

~/anaconda3/lib/python3.8/site-packages/dust_extinction/parameter_averages.py in evaluate(self, in_x, Rv)
   1212 
   1213         # check that the wavenumbers are within the defined range
-> 1214         _test_valid_x_range(x, self.x_range, self.__class__.__name__)
   1215 
   1216         # just in case someone calls evaluate explicitly

~/anaconda3/lib/python3.8/site-packages/dust_extinction/helpers.py in _test_valid_x_range(x, x_range, outname)
     59     """
     60     if np.logical_or(np.any(x < x_range[0]), np.any(x > x_range[1])):
---> 61         raise ValueError(
     62             "Input x outside of range defined for "
     63             + outname

ValueError: Input x outside of range defined for F19 [0.3 <= x <= 8.7, x has units 1/micron]
```

**Comment by karllark** [comment] 2022-04-05 13:24
> When using `make_extinguished_sed_grid`, the function behaves unexpectedly. For example, when I define `rv=[2.0, 6.0, 1.0]`, but don't define fA, it claims there is an Rv input parameter error.

This makes sense.  As you are defining a RvFALaw, then it expects the fA.  If you don't want fA, then just define an RvLaw only.
`extLaw = extinction.Generalized_DustExt(curve='F19')`

**Comment by karllark** [comment] 2022-04-05 13:25
The x outside the allowed range error is caused by asking for the extinction to be calculated outside of the allowed wavelength range (x = 1/lambda in microns).

**Comment by christinawlindberg** [comment] 2022-04-05 20:23
Do you know what sets the wavelength range? I would have thought it would be the filters specified in the beast_settings file, but when I restrict them to just visible bands, it still throws me that error.

**Comment by karllark** [comment] 2022-04-06 10:47
Are you including any additional filters?  E.g., for ionizing photons?  A bit more detail would be helpful for understanding this issue.   What is this work for?

**Comment by christinawlindberg** [comment] 2022-04-13 19:37
Issue has been resolved! Turns out I had missed assigning `extLaw=extLaw` in `make_spectral_grid` beforehand, so the wavelength range hadn't been trimmed beforehand since the following code in `make_spectral_grid` was never run:

```
            # extinction
            if extLaw is not None:

                ext_law_range_A = 1e4 / np.array(extLaw.x_range)
                valid_lambda = np.where(
                    (g.lamb > np.min(ext_law_range_A))
                    & (g.lamb < np.max(ext_law_range_A))
                )[0]

                g.lamb = g.lamb[valid_lambda]
                g.seds = g.seds[:, valid_lambda]
```

Perhaps the code snippet above should also be run in `make_extinguished_sed_grid` since I don't see why specifying an extinction law should be required for first generating a spectral grid and then later applying the extinction effects.

**Comment by karllark** [comment] 2022-04-14 13:09
The extinction law is specified there for ease in later processing.  It might be able to be moved, but I think it serves the purpose of cropping the wavelength range before the *dust-free* photometry is computed.  This saves computing it multiple times for the dust-free case in `make_extinguished_sed_grid`.

**Comment by karllark** [comment] 2022-04-14 13:10
Closing this issue.  Please open a new issue if you want to push for moving the extinction curve based wavelength trimming to the latter function.

**Closed by karllark** 2022-04-14 13:10 UTC
Labels: question
